import yaml

config_data = {}

with open("config.yaml", "r") as yamlfile:
    config_data = yaml.load(yamlfile, Loader=yaml.FullLoader)


API_TOKEN = config_data["BOT"]["TOKEN"]

TG_POINTS = config_data["TG_POINTS"]
BASE_COMMENT_POINTS = TG_POINTS["BASE_COMMENT_POINTS"]
PRESTIGE_LEVEL_ADDED_MULTIPLIER = TG_POINTS["PRESTIGE_LEVEL_ADDED_MULTIPLIER"]
BASE_ACCEPTED_TIKTOK_PRAISE = TG_POINTS["BASE_ACCEPTED_TIKTOK_PRAISE"]
BASE_FIRE_TIKTOK_PRAISE = TG_POINTS["BASE_FIRE_TIKTOK_PRAISE"]
BASE_REJECTED_TIKTOK_PRAISE = TG_POINTS["BASE_REJECTED_TIKTOK_PRAISE"]
BASE_MAX_TIKTOK_POINTS = TG_POINTS["BASE_MAX_TIKTOK_POINTS"]

